name: misc_notebooks

channels:
  - conda-forge
  - anaconda
  - damianavila82

dependencies:
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - sympy
  - altair
  - vega_datasets
  - vega
  - bokeh
  - pandas
  - rise

  # extensions
  - jupyter_contrib_nbextensions
  - nbgrader

